services:
  ubuntu-app:
    build:
      context: ./ubuntu
    container_name: ubuntu-data-loader
    hostname: ubuntu_worker
    networks:
      - data_net
    volumes:
      - ubuntu_data:/app/data

    command: tail -f /dev/null 


networks:
  data_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"


volumes:
  ubuntu_data:
