services:
  ubuntu-app:
    build:
      context: ./ubuntu
    container_name: ubuntu-data-loader
    hostname: ubuntu_worker
    networks:
      - data_net
    volumes:
      - ubuntu_data:/app/data

    command: tail -f /dev/null

  db:
    build:
      context: ./db
    container_name: postgres-db
    hostname: pgdb
    networks:
      - data_net
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  data_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"


volumes:
  ubuntu_data:
  db_data:
